// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ60iUmzZEa8gi_Jtzw5xG3aLtT4jxPXI',
    appId: '1:948516375676:web:9be374dcac7965e8194df9',
    messagingSenderId: '948516375676',
    projectId: 'capstone-c22-117',
    authDomain: 'capstone-c22-117.firebaseapp.com',
    storageBucket: 'capstone-c22-117.appspot.com',
    measurementId: 'G-XJZ86VN0LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-MLyNSfRmDj-aSSoU5tRdJQLKSJNqTnw',
    appId: '1:948516375676:android:9f03ac6fbd5e5b90194df9',
    messagingSenderId: '948516375676',
    projectId: 'capstone-c22-117',
    storageBucket: 'capstone-c22-117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoifSIszGFBOLjvZJn9W6CiKYV8Avz-dQ',
    appId: '1:948516375676:ios:1fa36eb9338346d5194df9',
    messagingSenderId: '948516375676',
    projectId: 'capstone-c22-117',
    storageBucket: 'capstone-c22-117.appspot.com',
    iosClientId: '948516375676-uv9kg69uaqaai2c6ej3rpfngp81ikbc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );
}
